-- 010_seed_catalog.sql — seed the vehicle_catalog table (50 cars + 40 motorcycles)
-- so the Admin → Catalog page has data. Safe to run once.

INSERT INTO vehicle_catalog (unit_type, make, model, category, fuel_type, est_km_per_liter)
SELECT * FROM (VALUES
('car','Toyota','Corolla','sedan','gasoline',13.5),
('car','Toyota','Yaris','sedan','gasoline',15),
('car','Toyota','Hilux','pickup','diesel',11),
('car','Toyota','RAV4','suv','gasoline',12),
('car','Toyota','Fortuner','suv','diesel',10.5),
('car','Hyundai','Accent','sedan','gasoline',14),
('car','Hyundai','Elantra','sedan','gasoline',13.5),
('car','Hyundai','Tucson','suv','gasoline',11.5),
('car','Hyundai','Santa Fe','suv','gasoline',10),
('car','Kia','Rio','sedan','gasoline',14.5),
('car','Kia','Sportage','suv','gasoline',11),
('car','Kia','Sorento','suv','gasoline',10.5),
('car','Nissan','Sentra','sedan','gasoline',13),
('car','Nissan','Versa','sedan','gasoline',14),
('car','Nissan','Frontier','pickup','diesel',10),
('car','Nissan','X-Trail','suv','gasoline',11.5),
('car','Honda','Civic','sedan','gasoline',14),
('car','Honda','CR-V','suv','gasoline',12),
('car','Honda','Fit','hatchback','gasoline',15.5),
('car','Mazda','3','sedan','gasoline',13.5),
('car','Mazda','CX-5','suv','gasoline',12),
('car','Chevrolet','Spark','hatchback','gasoline',16),
('car','Chevrolet','Aveo','sedan','gasoline',14),
('car','Chevrolet','Sail','sedan','gasoline',14.5),
('car','Chevrolet','D-Max','pickup','diesel',10.5),
('car','Suzuki','Swift','hatchback','gasoline',16),
('car','Suzuki','Vitara','suv','gasoline',12.5),
('car','Suzuki','Jimny','suv','gasoline',13),
('car','Mitsubishi','Lancer','sedan','gasoline',13),
('car','Mitsubishi','Montero Sport','suv','diesel',10),
('car','Mitsubishi','Outlander','suv','gasoline',11),
('car','Ford','Fiesta','hatchback','gasoline',14.5),
('car','Ford','Focus','sedan','gasoline',13.5),
('car','Ford','Ranger','pickup','diesel',10),
('car','Ford','Escape','suv','gasoline',11.5),
('car','Volkswagen','Jetta','sedan','gasoline',13),
('car','Volkswagen','Gol','hatchback','gasoline',14),
('car','Volkswagen','Tiguan','suv','gasoline',11),
('car','Peugeot','208','hatchback','gasoline',15),
('car','Peugeot','301','sedan','gasoline',14),
('car','Renault','Logan','sedan','gasoline',14.5),
('car','Renault','Duster','suv','gasoline',12),
('car','Geely','CK','sedan','gasoline',14),
('car','Geely','Emgrand','sedan','gasoline',13.5),
('car','Chery','QQ','hatchback','gasoline',16.5),
('car','Chery','Tiggo 2','suv','gasoline',12),
('car','BYD','F3','sedan','gasoline',14),
('car','BYD','Yuan Plus','suv','electric',25),
('car','Isuzu','D-Max','pickup','diesel',10.5),
('car','Great Wall','Wingle 5','pickup','diesel',10),
('motorcycle','Honda','CB110',NULL,'gasoline',45),
('motorcycle','Honda','Wave 110',NULL,'gasoline',48),
('motorcycle','Honda','XR190',NULL,'gasoline',35),
('motorcycle','Honda','CB125F',NULL,'gasoline',42),
('motorcycle','Honda','CB190R',NULL,'gasoline',38),
('motorcycle','Yamaha','YBR125',NULL,'gasoline',40),
('motorcycle','Yamaha','FZ150',NULL,'gasoline',38),
('motorcycle','Yamaha','XTZ125',NULL,'gasoline',42),
('motorcycle','Yamaha','Crypton',NULL,'gasoline',50),
('motorcycle','Yamaha','Fazer 250',NULL,'gasoline',32),
('motorcycle','Suzuki','GN125',NULL,'gasoline',42),
('motorcycle','Suzuki','Gixxer 150',NULL,'gasoline',40),
('motorcycle','Suzuki','Burgman 125',NULL,'gasoline',38),
('motorcycle','Suzuki','DR200',NULL,'gasoline',35),
('motorcycle','Bajaj','Boxer 150',NULL,'gasoline',45),
('motorcycle','Bajaj','Pulsar 150',NULL,'gasoline',40),
('motorcycle','Bajaj','Pulsar 200',NULL,'gasoline',35),
('motorcycle','Bajaj','Discover 125',NULL,'gasoline',48),
('motorcycle','TVS','Apache 160',NULL,'gasoline',38),
('motorcycle','TVS','Star City',NULL,'gasoline',50),
('motorcycle','TVS','XL100',NULL,'gasoline',55),
('motorcycle','Kawasaki','Z125',NULL,'gasoline',40),
('motorcycle','Kawasaki','Ninja 250',NULL,'gasoline',30),
('motorcycle','Italika','FT150',NULL,'gasoline',42),
('motorcycle','Italika','DM200',NULL,'gasoline',35),
('motorcycle','Italika','RT110',NULL,'gasoline',48),
('motorcycle','Vento','Workman 150',NULL,'gasoline',40),
('motorcycle','Vento','Rocketman 250',NULL,'gasoline',32),
('motorcycle','Vento','Street Rod 150',NULL,'gasoline',38),
('motorcycle','Keeway','RKV200',NULL,'gasoline',35),
('motorcycle','Keeway','Superlight 150',NULL,'gasoline',40),
('motorcycle','Lifan','LF150',NULL,'gasoline',42),
('motorcycle','Lifan','KPR200',NULL,'gasoline',35),
('motorcycle','Zongshen','ZS150',NULL,'gasoline',42),
('motorcycle','Zongshen','ZS200',NULL,'gasoline',38),
('motorcycle','Hero','Hunk 150',NULL,'gasoline',42),
('motorcycle','Hero','Splendor',NULL,'gasoline',50),
('motorcycle','AKT','TTR200',NULL,'gasoline',35),
('motorcycle','AKT','Special 110',NULL,'gasoline',48),
('motorcycle','UM','Renegade 200',NULL,'gasoline',35)
) AS v(unit_type, make, model, category, fuel_type, est_km_per_liter)
WHERE NOT EXISTS (SELECT 1 FROM vehicle_catalog x WHERE x.make = v.make AND x.model = v.model);
