import {
  CircleDollarSign,
  ScrollText,
  LineChart,
  CarFront,
  SlidersHorizontal,
  Route,
  TrendingUp,
  ShieldCheck,
  WifiOff,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Search,
  Check,
  X,
  Car,
  Fuel,
  Gauge,
  Mail,
  LogOut,
  Trash2,
  RefreshCw,
  Users,
  LayoutDashboard,
  CreditCard,
  Megaphone,
  Package,
  Plus,
  Pencil,
  Cloud,
  CloudOff,
  Lock,
  Menu,
  Bell,
  UserCircle,
  Crown,
  Navigation,
  Play,
  Pause,
  Square,
  Download,
  FileText,
  Users2,
  Copy,
  Upload,
  Clock,
  CalendarDays,
  Image as ImageIcon,
  Bell as BellRing,
  Bike,
  Eye,
  EyeOff,
  ArrowLeft,
  CheckCircle2,
  AlertCircle,
  Info,
  Loader2,
  KeyRound,
  MailCheck,
  type LucideIcon,
} from 'lucide-react';

/** Premium Lucide icons — strokeWidth 1.75 for crisp UI */
export const iconProps = {
  strokeWidth: 1.75,
  size: 22,
} as const;

export const iconPropsSm = {
  strokeWidth: 1.75,
  size: 20,
} as const;

export const iconPropsLg = {
  strokeWidth: 1.5,
  size: 28,
} as const;

export const AppIcons = {
  calculator: CircleDollarSign,
  history: ScrollText,
  reports: LineChart,
  vehicle: CarFront,
  settings: SlidersHorizontal,
  onboarding: {
    route: Route,
    trend: TrendingUp,
    shield: ShieldCheck,
  },
  offline: WifiOff,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  search: Search,
  check: Check,
  close: X,
  car: Car,
  motorcycle: Bike,
  fuel: Fuel,
  gauge: Gauge,
  // Stage 2
  mail: Mail,
  logout: LogOut,
  trash: Trash2,
  sync: RefreshCw,
  users: Users,
  dashboard: LayoutDashboard,
  billing: CreditCard,
  announce: Megaphone,
  catalog: Package,
  plus: Plus,
  edit: Pencil,
  cloud: Cloud,
  cloudOff: CloudOff,
  lock: Lock,
  menu: Menu,
  bell: Bell,
  account: UserCircle,
  crown: Crown,
  shieldCheck: ShieldCheck,
  gps: Navigation,
  play: Play,
  pause: Pause,
  stop: Square,
  download: Download,
  pdf: FileText,
  fleet: Users2,
  reminder: BellRing,
  copy: Copy,
  upload: Upload,
  clock: Clock,
  calendar: CalendarDays,
  image: ImageIcon,
  eye: Eye,
  eyeOff: EyeOff,
  back: ArrowLeft,
  success: CheckCircle2,
  alert: AlertCircle,
  info: Info,
  spinner: Loader2,
  key: KeyRound,
  mailCheck: MailCheck,
} as const;

export type AppIconName = keyof typeof AppIcons;

export function isLucideIcon(v: unknown): v is LucideIcon {
  return typeof v === 'function';
}
